apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: k8swebapp
  name: k8swebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      application: k8swebapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
        application: k8swebapp
    spec:
      containers:
      - name: k8swebapp
        image: docker.io/abalasu1/springappmonitoring
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10          
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
