apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: ibm-nginx-dev
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
    
