apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      datacenter: Hursley
      region: EU
  resourceHint:
    type: cpu
