apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: calculator
  namespace: mcm-calculator
  labels:
    app: calculator
spec:
  selector:
    matchLabels:
      app: calculator
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
    
