apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: multiserviceapp
  namespace: multiserviceapp
  labels:
    app: multiserviceapp
spec:
  selector:
    matchLabels:
      app: multiserviceapp
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
    
