server:
  port: 8080
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
  endpoint:
    shutdown:
      enabled: true
      
  metrics:
    tags:
      application: SpringApp
      environment: dev      
      
endpoints:
  prometheus:
    id: metrics 
    
info:
  app:
    name: Spring Demo app 
    description: Spring Demo to show monitoring with prometheus and grafana
    version: 1.0.0