apiVersion: v1
kind: Service
metadata:
  name: svc-add
  namespace: mcm-simpleapp
  labels:
    app: add    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: add