apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add
  namespace: simpleapp
  labels:
    app: add     
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add    
  template:
    metadata:
      labels:
        app: add         
    spec:
      containers:
      - image: arunimi/add:v1.0.0
        name: addcontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: addport
