apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compositeop
  namespace: simpleapp
  labels:
    app: compositeop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compositeop
  template:
    metadata:
      labels:
        app: compositeop
    spec:
      containers:
      - image: arunimi/compositeop:v1.0.0
        name: compositeopcontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: compoopport
        env:
        - name: VERSION
          value: "v1.0.0"
        - name: ADDURI
          value: "http://svcadd.simpleapp:8080/basicop/add"
        - name: SUBURI
          value: "http://svcsubtract.simpleapp:8080/basicop/subtract"
        - name: MULURI
          value: "http://svcmultiply.simpleapp:8080/basicop/multiply"
        - name: DIVURI
          value: "http://svcdivide.simpleapp:8080/basicop/divide"
