apiVersion: v1
kind: Service
metadata:
  name: svc-divide
  namespace: mcm-simpleapp
  labels:
    app: divide     
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: divide