apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: divide
  namespace: simpleapp
  labels:
    app: divide   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
  template:
    metadata:
      labels:
        app: divide
    spec:
      containers:
      - image: arunimi/divide:v1.0.0
        name: dividecontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: divideport