apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multiply
  namespace: simpleapp
  labels:
    app: multiply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
    spec:
      containers:
      - image: arunimi/multiply:v1.0.0
        name: multiplycontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: multiplyport