apiVersion: v1
kind: Service
metadata:
  name: svcmultiply
  namespace: simpleapp
  labels:
    app: multiply
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: multiply