apiVersion: v1
kind: Service
metadata:
  name: svc-multiply
  namespace: mcm-simpleapp
  labels:
    app: multiply     
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: multiply