apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiprocessor
  namespace: simpleapp
  labels:
    app: processor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - image: arunimi/processor:v1.0.0
        name: processorcontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: processorport
        env:
        - name: OPSERVICEHOST
          value: "http://svccompositeop.simpleapp"
        - name: OPSERVICEPORT
          value: "8080"
