apiVersion: v1
kind: Service
metadata:
  name: svcprocessor
  namespace: simpleapp
  labels:
    app: processor  
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: processor