apiVersion: v1
kind: Service
metadata:
  name: svc-subtract
  namespace: simpleapp
  labels:
    app: subtract   
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: subtract
