apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subtract
  namespace: simpleapp
  labels:
    app: subtract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtract
  template:
    metadata:
      labels:
        app: subtract
    spec:
      containers:
      - image: arunimi/subtract:v1.0.0
        name: subtractcontainer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: subtractport