apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: simpleapp  
  labels:
    app: ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: uicontainer
        image: arunimi/ui:v1.0.0
        imagePullPolicy: Always  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: httpserver
