apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: simpleapp
  labels:
    app: ui
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  selector:
    app: ui
