spring:
  profiles:
    active: development
  application:
    name: processor
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0      
    
server:
  port: 8006
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod
---
spring:
  profiles: development
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
          processor-in:
            destination: expressionset
            contentType: application/json
          processor-out:
            destination: expressionset
            contentType: application/json
                     
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8101/eureka}
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka:9092
      bindings:
          processor-in:
            destination: expressionset
            contentType: application/json
          processor-out:
            destination: expressionset
            contentType: application/json  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery:8101/eureka}  