apiVersion: v1
kind: Service
metadata:
  name: svc-add
  namespace: {{ .Values.backendns }}
  labels:
    app: add
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: add
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add
  namespace: {{ .Values.backendns }}
  labels:
    app: add
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: add    
  template:
    metadata:
      labels:
        app: add         
    spec:
      containers:
      - image: {{ .Values.image.add }}
        name: add-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: add-port
---
apiVersion: v1
kind: Service
metadata:
  name: svc-subtract
  namespace: {{ .Values.backendns }}
  labels:
    app: subtract
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: subtract
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subtract
  namespace: {{ .Values.backendns }}
  labels:
    app: subtract
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: subtract    
  template:
    metadata:
      labels:
        app: subtract         
    spec:
      containers:
      - image: {{ .Values.image.subtract }}
        name: subtract-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: subtract-port
---
apiVersion: v1
kind: Service
metadata:
  name: svc-multiply
  namespace: {{ .Values.backendns }}
  labels:
    app: multiply
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: multiply
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multiply
  namespace: {{ .Values.backendns }}
  labels:
    app: multiply
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multiply     
  template:
    metadata:
      labels:
        app: multiply         
    spec:
      containers:
      - image: {{ .Values.image.multiply }}
        name: multiply-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: multiply-port
---
apiVersion: v1
kind: Service
metadata:
  name: svc-divide
  namespace: {{ .Values.backendns }}
  labels:
    app: divide
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: divide
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: divide
  namespace: {{ .Values.backendns }}
  labels:
    app: divide
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: divide    
  template:
    metadata:
      labels:
        app: divide         
    spec:
      containers:
      - image: {{ .Values.image.divide }}
        name: divide-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: divide-port
---
apiVersion: v1
kind: Service
metadata:
  name: svc-compositeop
  namespace: {{ .Values.backendns }}
  labels:
    app: compositeop
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: compositeop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compositeop
  namespace: {{ .Values.backendns }}
  labels:
    app: compositeop
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: compositeop       
  template:
    metadata:
      labels:
        app: compositeop       
    spec:
      containers:
      - image: {{ .Values.image.compositeop }}
        name: compositeop-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: compoop-port
        env:
        - name: VERSION
          value: "v1.0.0"        
        - name: ADDURI
          value: "http://svc-add.mcm-simpleapp:8080/basicop/add"
        - name: SUBURI
          value: "http://svc-subtract.mcm-simpleapp:8080/basicop/subtract"
        - name: MULURI
          value: "http://svc-multiply.mcm-simpleapp:8080/basicop/multiply"
        - name: DIVURI
          value: "http://svc-divide.mcm-simpleapp:8080/basicop/divide"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmdpod
  namespace: {{ .Values.backendns }}
  labels:
    app: cmdpodbe
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cmdpodbe    
  template:
    metadata:
      labels:
        app: cmdpodbe         
    spec:
      containers:
      - image: tutum/curl
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]      
        name: cmdpod-container
        imagePullPolicy: Always
