apiVersion: v1
kind: Service
metadata:
  name: svc-processor
  namespace: {{ .Values.frontendns }}
  labels:
    app: processor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}     
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: processor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-processor
  namespace: {{ .Values.frontendns }}
  labels:
    app: processor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}     
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: processor    
  template:
    metadata:
      labels:
        app: processor         
    spec:
      containers:
      - image: {{ .Values.image.processor }}
        name: processor-container
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: processor-port
        env:
        - name: OPSERVICEHOST
          value: "http://svc-compositeop.calc-backend"
        - name: OPSERVICEPORT
          value: "8080"          
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.frontendns }}
  labels:
    app: ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}     
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  selector:
    app: ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.frontendns }}  
  labels:
    app: ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}     
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui       
    spec:
      containers:
      - name: ui-container
        image: {{ .Values.image.ui }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}   
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: http-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmdpod
  namespace: {{ .Values.frontendns }}
  labels:
    app: cmdpodfe
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}     
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cmdpodfe    
  template:
    metadata:
      labels:
        app: cmdpodfe         
    spec:
      containers:
      - image: tutum/curl
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]      
        name: debug-container
        imagePullPolicy: Always
