apiVersion: v1
kind: Service
metadata:
  labels:
    application: k8swebapp
  name: k8swebapp
  annotations:
    prometheus.io/scrape: 'true' 
    prometheus.io/path: '/actuator/prometheus' 
spec:
  selector:
    application: k8swebapp
  type: LoadBalancer
  ports:
  - name: webapp
    port: 80
    protocol: TCP
    targetPort: 8080